group <- c(rep(c("a","b"),c(length(phenotype1),length(phenotype2))))
design <- model.matrix(~0+factor(group))
#dge <- DGEList(counts=bulk_dataset)
#dge1 <- calcNormFactors(dge)
#bulk_dataset<-voom(dge1,design,normalize="quantile")
colnames(design) = levels(factor(group))
rownames(design) = colnames(bulk_dataset)
contrast.matrix <- makeContrasts("a-b", levels = design)
fit <- lmFit(bulk_dataset,design)
fit2 <- contrasts.fit(fit,contrast.matrix)
fit2 <- eBayes(fit2)
DEG_ot <- topTable(fit2, coef =1, n = Inf)
DEGs<-subset(DEG_ot, abs(DEG_ot$logFC)>1&DEG_ot$P.Value<0.05)
