library(Seurat)
Seurat_tmp <- CreateSeuratObject(counts = sc_dataset, project = "Single_Cell", min.cells = 400, min.features = 0)
Seurat_tmp <- NormalizeData(object = Seurat_tmp, normalization.method = "LogNormalize", scale.factor = 10000, verbose = F)
Seurat_tmp <- FindVariableFeatures(Seurat_tmp, selection.method = "vst", verbose = F)
Seurat_tmp <- ScaleData(Seurat_tmp, verbose = F)
Seurat_tmp <- RunPCA(Seurat_tmp, features = VariableFeatures(Seurat_tmp), verbose = F)
Seurat_tmp <- FindNeighbors(Seurat_tmp, dims = 1:10, verbose = F)
network  <- as.matrix(Seurat_tmp@graphs$RNA_snn)
library(Matrix)
snn=as(network, "dgCMatrix")
snn_df=as.data.frame(summary(snn))
library(igraph)
colnames(snn_df) <- c("from", "to", "weight")
g <- graph_from_data_frame(snn_df, directed = FALSE)
set.seed(0)
library(leidenAlg)
leiden<-leiden.community(g,resolution=0.6)
membership<-leiden[["membership"]]
index<-match(c(1:ncol(sc_dataset)),as.numeric(names(membership)))
leidengroup<-as.numeric(membership[index])
